#  Assign Behaviours to a Python Function Based on Data Types With Functools Singledispatch

In [9]:
import pandas as pd
from functools import singledispatch

In [15]:
@singledispatch
def create_data(data):
    raise NotImplementedError(f'Type {type(data)} is unsupported')

@create_data.register(dict)
def create_data_from_dict(data):
    print(f'Data is created from a {type(data)}')

    return pd.DataFrame(data)

@create_data.register(list)
@create_data.register(tuple)
def create_data_from_list(data):
    print(f'Data is created from a {type(data)}')

    return pd.DataFrame(data)

In [5]:
data_dict = {'a': [1, 2, 3], 'b': [4, 5, 6]}

In [16]:
create_data(data_dict)

Data is created from a <class 'dict'>

   a  b
0  1  4
1  2  5
2  3  6

In [ ]:
data_list = [(1,2), (2, 5), (3, 6)]

In [17]:
create_data(data_list)

Data is created from a <class 'list'>

   0  1
0  1  2
1  2  5
2  3  6

In [12]:
data_tuple = ((1,2), (2, 5), (3, 6))

In [18]:
create_data(data_tuple)

Data is created from a <class 'tuple'>

   0  1
0  1  2
1  2  5
2  3  6